branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode7.1
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - cd Example/Objective-C
    - pod install
script:
    - xcodebuild -workspace StylizeDemo.xcworkspace -scheme 'StylizeDemo' -sdk iphonesimulator build | xcpretty -c
