language: objective-c

osx_image: beta-xcode6.3

before_install:
    - sudo gem update --system
    - sudo gem install cocoapods
    - cd Example/Objective-C
    - cd ..

script:
    - xcodebuild build -workspace Objective-C/StylizeDemo.xcworkspace -scheme StylizeDemo -destination 'platform=iOS Simulator,name=iPhone 5,OS=latest'
