# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'StylizeDemo' do
    pod 'AsyncDisplayKit'
    pod 'Masonry'
    pod 'GRMustache'
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod "NSLogger"
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'Ono', '~>1.2.2'
    #pod 'stylize'
end

target 'StylizeDemoTests' do

end

